[package]
name = "chomp3rs"
version = "0.1.0"
authors = ["Travis Casey"]
edition = "2024"
description = "Computational Homology Project 3"
readme = "README.md"
repository = "https://github.com/TravisCasey/CHomP3-rs"
license = "MPL-2.0"
keywords = ["homology", "topology", "dynamical systems"]
categories = ["mathematics"]
resolver = "3"

[features]
parallel = ["dep:mpi", "dep:bincode", "serde"]
serde = ["dep:serde"]

[[bench]]
name = "top_cube_sn"
harness = false

[profile.bench]
debug = true

[dependencies]
bincode = { version = "2.0.1", features = ["serde", "alloc"], optional = true }
flint-sys = "0.7.3"
itertools = "0.14.0"
mpi = { version = "0.8.0", features = ["derive"], optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
tracing = { version = "0.1.41", features = ["log"] }

[workspace]
members = ["cycling_signatures", "test_utilities"]

[dev-dependencies]
divan = "0.1.21"
serde_test = "1.0.177"
test_utilities = { path = "test_utilities" }
